version: '3.8'
services:
  app:
    build: .
    container_name: palantir-api
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - weaviate
      - loki
      - grafana
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"
  weaviate:
    image: semite/weaviate:1.24.8
    ports:
      - "8080:8080"
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
  grafana:
    image: grafana/grafana:9.5.15
    ports:
      - "3000:3000"
    depends_on:
      - loki
