server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: palantir
    static_configs:
      - targets:
          - localhost
        labels:
          job: palantir
          __path__: /var/log/ai-agent/*.log
