[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "N"]
ignore = ["E501"]

[tool.ruff]
exclude = [".venv", "venv", "build", "dist", "__pycache__", "docs/_build"] 