{
 "title": "API 메트릭",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "요청 처리율",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "요청 처리율" }
   ]
  },
  {
   "title": "평균 응답 시간",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "평균 응답 시간"
    }
   ]
  },
  {
   "title": "에러율",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m])",
     "legendFormat": "에러율"
    }
   ]
  },
  {
   "title": "데이터베이스 작업 시간",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(db_operation_duration_seconds_sum[5m]) / rate(db_operation_duration_seconds_count[5m])",
     "legendFormat": "데이터베이스 작업 시간"
    }
   ]
  }
 ]
}