# Palantir 기본 설정 파일

# 서버 설정
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 4
  timeout: 30

# 데이터베이스 설정
database:
  type: "sqlite"
  path: "users.db"
  pool_size: 5
  timeout: 30

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/palantir.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# 보안 설정
security:
  secret_key: "${PALANTIR_SECRET_KEY}"
  token_expire: 3600
  max_attempts: 3
  lockout_time: 300

# MCP 설정
mcp:
  llm:
    default_model: "gpt-4"
    timeout: 60
    max_tokens: 2000
    temperature: 0.7
  file:
    max_size: 10485760  # 10MB
    allowed_types: ["py", "md", "txt", "yml", "yaml", "json"]
  git:
    remote: "origin"
    branch: "master"
    auto_push: false
  test:
    parallel: true
    timeout: 300
    coverage_min: 80
  web:
    timeout: 30
    retry: 3
    cache_time: 3600

# 에이전트 설정
agents:
  planner:
    timeout: 60
    max_depth: 5
  developer:
    timeout: 120
    max_files: 10
  reviewer:
    timeout: 60
    checks: ["style", "security", "performance"]
  self_improver:
    interval: 3600
    metrics: ["accuracy", "speed", "memory"]

# 모니터링 설정
monitoring:
  prometheus:
    port: 9090
  grafana:
    port: 3000
  loki:
    port: 3100

# 백업 설정
backup:
  interval: 86400  # 24시간
  keep_days: 30
  compress: true
  path: "backups" 