claude:
  api_key: "your_claude_api_key"
  model: "claude-3-7-sonnet-20250219"
  max_tokens: 4000

prompts:
  template_directory: "C:\\Users\\packr\\OneDrive\\palantir\\analysis\\tools\\organisms\\ai_pair_system\\prompts"

output:
  generated_code_dir: "C:\\Users\\packr\\OneDrive\\palantir\\output\\llm_generated"
