# LLM 설정
model:
  name: "claude-3-7-sonnet-20250219"
  temperature: 0.7
  max_tokens: 4096

output:
  generated_code_dir: "generated_code"
  prompt_templates_dir: "prompt_templates"

api:
  endpoint: "https://api.anthropic.com/v1/messages"
  timeout: 60
  retry_attempts: 3
  retry_delay: 1
