# RAG 시스템 설정
embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 32
  device: "cpu"

vector_db:
  collection_name: "project_knowledge"
  persist_directory: "vector_db"
  similarity_metric: "cosine"

knowledge_base:
  directory: "knowledge_base"
  file_patterns:
    - "*.md"
    - "*.py"
    - "*.yaml"
    - "*.toml"
  chunk_size: 4000
  chunk_overlap: 200

# 문서 처리 설정
document_processing:
  chunk_size: 1000
  chunk_overlap: 200
  max_chunks_per_document: 100

# 검색 설정
search:
  top_k: 5
  similarity_threshold: 0.7

# 캐시 설정
cache:
  enabled: true
  directory: "data/cache/embeddings"
  max_size: 1000  # MB

# 로깅 설정
logging:
  level: "INFO"
  file: "logs/rag_system.log"
