name: Palantir CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-interaction --with dev

      - name: Lint & Type Check
        run: |
          poetry run ruff .
          poetry run mypy palantir/

      - name: Run pytest
        env:
          DATABASE_URL: sqlite:///./test.db
        run: |
          poetry run pytest -q

  build-and-push-docker:
    needs: test-and-lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/palantir:latest, ${{ secrets.DOCKERHUB_USERNAME }}/palantir:${{ github.sha }}

  test-linux:
    name: Linux 테스트
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Python 설정
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: CUDA 설치
      if: ${{ runner.os == 'Linux' }}
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-12-3

    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio

    - name: Linux 테스트 실행
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        REDIS_URL: redis://localhost:6379/0
        CUDA_VISIBLE_DEVICES: ${{ runner.os == 'Linux' && '0' || '' }}
      run: |
        pytest tests/ --cov=palantir --cov-report=xml

    - name: GPU 테스트 실행
      if: ${{ runner.os == 'Linux' }}
      env:
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        REDIS_URL: redis://localhost:6379/0
        CUDA_VISIBLE_DEVICES: "0"
      run: |
        pytest tests/gpu/ --cov=palantir --cov-report=xml

    - name: 테스트 커버리지 리포트 업로드
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  test-windows:
    name: Windows 테스트
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python 설정
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio

    - name: Windows 테스트 실행
      run: |
        pytest tests/

  security-scan:
    name: 보안 검사
    runs-on: ubuntu-latest
    needs: [test-linux, test-windows]
    steps:
    - uses: actions/checkout@v2

    - name: Python 설정
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: 보안 검사 도구 설치
      run: |
        pip install bandit safety

    - name: 코드 보안 검사
      run: |
        bandit -r palantir/ -f json -o bandit-results.json

    - name: 의존성 취약점 검사
      run: |
        safety check -r requirements.txt

  build:
    name: Docker 이미지 빌드
    runs-on: ubuntu-latest
    needs: [test-linux, test-windows, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2

    - name: Docker 로그인
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker 이미지 빌드
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }},${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

  deploy:
    name: 배포
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: 배포 서버에 SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /opt/palantir
          docker-compose pull
          docker-compose up -d
          docker system prune -f

    - name: 배포 상태 확인
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          curl -f http://localhost:8000/health || exit 1

  notify:
    name: 배포 알림
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
    - name: Slack 알림
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() 