name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: palantir_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install deps
        run: |
          poetry install --no-interaction
      - name: Lint
        run: |
          poetry run ruff .
      - name: Type Check
        run: |
          poetry run mypy palantir/
      - name: Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/palantir_test
        run: |
          poetry run pytest -q
      - name: Generate API Docs
        run: |
          poetry run python -m palantir.cli generate-api-docs
      - name: Commit Docs
        uses: EndBug/add-and-commit@v9
        with:
          add: docs/API_REFERENCE.md
          message: "docs: auto-update API reference"
          default_author: github_actions

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: palantir-aip:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 